spring-financial-group/jx3-openapi-generation

pipeline/generate-package.yaml, pipeline/generate-preview-package.yaml
=> add some common pipelines for package creation

CreateCsharpPackage.sh, Dockerfile, pipeline/generate-csharp-package.yaml, spec.json
Created csharp package shell script
Created generate csharp package yaml
Added dotnet commands to Dockerfile
=> Initial Upload

pipeline/generate-preview-package-v3.yaml
fix pod ip not found in generate-preview-package-v3.yaml
=> fix cat no url

CreateCsharpPackage.sh, pipeline/generate-csharp-package.yaml, pipeline/generate-preview-csharp-package.yaml
As requested by Victor via Slack
=> Added generate-preview-csharp-package.yaml

CreateAngularPackageV2.sh, CreateAngularPackageV3.sh, CreateCsharpPackage.sh
force http 1.1 to fix http 2 framing layer error.
=> force http 1.1

CreateAngularPackageV2.sh, CreateAngularPackageV3.sh, CreateCsharpPackage.sh
fix bug in pipeline with ssl cert validation.
=> fix bug with cert valiadation

pipeline/generate-package-v3.yaml, pipeline/generate-preview-package-v3.yaml
update with fixed curl cert validation
=> update package version for gen-package-v3 and gen-preview-package-v3

pipeline/generate-csharp-package-nonapigw.yaml, pipeline/generate-csharp-package.yaml, pipeline/generate-java-package-v3.yaml, pipeline/generate-package-v3.yaml, pipeline/generate-package.yaml, pipeline/generate-preview-csharp-calcvalues-package.yaml, pipeline/generate-preview-csharp-package.yaml, pipeline/generate-preview-golang-csharp-package.yaml, pipeline/generate-preview-golang-package-v3.yaml, pipeline/generate-preview-java-package-v3.yaml, pipeline/generate-preview-package-v3.yaml, pipeline/generate-preview-package.yaml
This reverts commit af78254a53e9b5970efc6f22ec9a8d68aa532e3c.
=> Re-enable in repo package generation

README.md
Adds an initial README just explaining how to use the package generation
=> feat: add initial README

Dockerfile
CSharp packages generating & pushing correctly
=> chore(csharp): update dotnet image

pipeline/generate-python-package.yaml
First casualty of the scream test
=> fix: use python310 for package gen

.lighthouse/jenkins-x/generate-test-packages.yaml, Dockerfile, openapitools.json, pkg/packageGenerator/base_generator.go, pkg/packageGenerator/python/generator.go
- Updating the openapi-generator-cli version
- Adding async generation for python using asyncio lib
=> feat: CLI version Upgrade

.lighthouse/jenkins-x/release.yaml
Forgot to update release pipeline golang version
=> fix: release go build version

Dockerfile, pkg/packageGenerator/go/generator.go
Generate Mock packages with mockery for generated clients and add directly to package
=> chore: create mock files for go clients

pkg/packageGenerator/go/generator.go
=> fix: Handle Swagger V2

pkg/packageGenerator/go/generator.go
Reviewers now removed correctly for go pkg
=> fix: remove reviewers porperly

.lighthouse/OWNERS, OWNERS, OWNERS_ALIASES
* Add infrastructure as owners
This is infra-esque
=> chore: infrastructure as OWNERS

.lighthouse/jenkins-x/pullrequest.yaml, .lighthouse/jenkins-x/release.yaml
Fix the PR pipeline push step..
=> fix: pr push step fix

mocks/swagger.json, openapitools.json
- set c# pkg gen library to restsharp
- set equatable to true 
In the change from 7.1.0 to 7.15.0, a couple of defaults were changed:
- https://github.com/OpenAPITools/openapi-generator/pull/20748
- https://github.com/OpenAPITools/openapi-generator/pull/17039
this PR sets the defaults to their values at 7.1.0, hopefully retaining the same behaviour.
=> fix: c# package generation 

pipeline/generate-packages-testing.yaml, pipeline/generate-packages.yaml, pipeline/generate-python-package.yaml
- fix pipes with git config changes
=> fix: update pipeline spec with git config

templates/java/gradle.properties
* Enable debug logging
Let's see what is going on.
=> feat(java): enable debug logging

templates/java/gradle.properties
* Increase timeouts further
Still borked.
=> chore: update gradle timeouts
